### ISSUE TITLE
does not display on my blog

### ISSUE THREAD

**Issue by darkzbaron** [kognetiks/chatbot-chatgpt#15]
I have isntalled the plugin but it does not display anything

**Comment by kognetiks** [comment]
Have you updated to Ver 1.6.6?

**Comment by kognetiks** [comment]
Did you add the short code [chatbot_chatgpt] to your site?

What theme are you using?

**Comment by darkzbaron** [comment]
Tried with no success

Here is my CSS any potential conflict?

/*loupe*/

.main-navigation .nav-right .icon-search {
	   font-size: 50px; /* Adjust as needed */
		filter: brightness(0) saturate(100%) invert(55%) sepia(97%) saturate(300%) hue-rotate(66deg) brightness(93%) contrast(92%);
}

@media screen and (max-width: 600px) {
  .main-navigation .nav-right .icon-search {
    margin: -27px auto;
  }
}

#hamburger-one {
    display: block;
    margin: 24px auto;
    height: 30px;
    position: relative;
    cursor: pointer;
	filter: brightness(0) saturate(100%) invert(55%) sepia(97%) saturate(300%) hue-rotate(66deg) brightness(93%) contrast(92%);
}
@media screen and (max-width: 600px) {
    #hamburger-one {
        margin: 0px auto;
    }
}

/* Change Post Content Font Color */
.entry-content,
.entry-title,
.post-description {
    color: #000000;
}


/* hide some article carousel on the homage page*/
.home .article-wrapper {
  display: none;
}
.home .nav-links {
  display: none;
}
.author-email {
    display: none !important;
    visibility: hidden !important;
}

img.custom-logo {
  z-index:-1 !important;
	max-height: 90px !important;
	max-width: 90px;
	/*
	position: relative;
   top: 200px;
   left: 100px;
	*/
	 
}
/*.shop-now-link {background-color: yellow;}
*/

.site{background-color: #d9d9d9;}
.site-branding{font-size : 35px;color:white;font-style: bold;}

/* element.style {
}
/*
.entry-meta .author-img {display:none;}

*/

.site-title{display:none;}
.be-author-details{display:none;}
.booster-block{display:none;}
.site-info{display:none;}
.twp-like-dislike-button{display:none;}
.entry-meta{font-size: 10px;}
.entry-title-big{font-size: 65px;text-transform: uppercase;}
.entry-title-small{text-transform: uppercase;}
.entry-title{text-transform: uppercase;}

/*
 this was preventing category and author to be displayed
.twp-plugin-title{display:none;} 
.article-wraper{display:none;}
*/

/*
.post-header + .post-content { margin-top: 25px; }
*/

.menu_item_wpglobus_menu_switch {width:200px;padding: 10px;}
.menu_item_wpglobus_menu_switch .sub-menu{width:200px;}
.menu_item_wpglobus_menu_switch .sub-menu:hover{width:200px;}
.menu_item_wpglobus_menu_switch li:hover > a{width:200px;}

**Comment by darkzbaron** [comment]
Happy to send you my theme file too if that helps

**Comment by kognetiks** [comment]
I've made some changes to ver 1.7.2 that might solve you issues.

Have you updated and tried again with the latest version?
