### ISSUE TITLE
 1.7.2 crashed after auto update install and got error 1.7.1 no longer found

### ISSUE THREAD

**Issue by sprinteroz** [kognetiks/chatbot-chatgpt#24]
Hi, 1.7.2 crashed after auto update install and got error 1.7.1 no longer found

**Comment by kognetiks** [comment]
Hello sprinteroz,

Thank you for letting me know.  Are you able to download 1.7.1 from here or the WP plugin directory?  Can you check your debug.log and see if there is anything of interest in there?

FYI, I ran an update from 1.7.1 to 1.7.2 this morning on one of my sites and didn't have a problem.  Please see if you can reinstall 1.7.2 and then update again.  Any error messages may help me understand what happened.

Stephen

**Comment by sprinteroz** [comment]
Thanks, I found it was deactivated after the update. I just had to reactivate the plugin again, it is all working now 👍
