### ISSUE TITLE
How do I find my custom GPT assistant ID, Do these GPT's need to be build in playground or chat GPT UI

### ISSUE THREAD

**Issue by sprinteroz** [kognetiks/chatbot-chatgpt#25]
How do I find my custom GPT assistant ID? Another question: Do these GPT's need to be build in playground or chat GPT UI?

**Comment by kognetiks** [comment]
Hello sprinteroz,

Yes, custom GTP assistants - for now anyway - need to be built in the OpenAI Playground.

OpenAI hasn't provided an API endpoint - yet - for Custom GPTs build in ChatGPT.

They work the same, but, they run a bit slower in the Playground.

Stephen

**Comment by sprinteroz** [comment]
ok thanks yeah i just found this as well in the documentation:  Discover more about these innovative features at [Kognetiks.com](https://kognetiks.com/wordpress-plugins/chatbot-chatgpt/chatbot-chatgpt-for-wordpress-assistants-and-custom-gpts/) and **_[OpenAI's Playground]_**(https://platform.openai.com/assistants).

**Comment by kognetiks** [comment]
Yes, they are essentially do the same job.  Assistants in the Playground have been around for a while.  We'll have to see if OpenAI will provide an endpoint to access the ones poeple build in ChatGPT.

**Comment by sprinteroz** [comment]
OK would it be hard for me to move my gpt'ss over to Playground? I have made these 2 gpt's
 "Mystic Oracle DB" [Mystic Oracle DB](https://chat.openai.com/g/g-PtXtUIH5n-mystic-oracle-db)
“Tattoo Imagineer” [Tattoo Imagineer ](https://chat.openai.com/g/g-L3KU4wXsk-tattoo-imagineer)

**Comment by kognetiks** [comment]
It's essentially the same process.  If you have source files and code, you just upload them there instead.

If the Tattoo Imagineer generates images, there may be limitations on what can be done in the Playground.

Let me know what you experience is with both of these.

**Comment by sprinteroz** [comment]
Ok Thanks, I will give playground a go, and will let you know if it all works out's, or if there are limitations with the image generation.
