### ISSUE TITLE
Instructions need updating (or its a bug)

### ISSUE THREAD

**Issue by mayurjobanputra** [kognetiks/chatbot-chatgpt#26]
Hi Stephen. Was doing the initial setup of this plugin. Went to knowledge tab, and there was no "yes" option. I chose "now" instead and clicked saved settings, but nothing happened as a result (from what I can see). 

See below

![image](https://github.com/kognetiks/chatbot-chatgpt/assets/6332663/2be64fe6-4259-45a0-918a-f1a4a9bc0c26)

**Comment by mayurjobanputra** [comment]
UPDATE: OK, so it did process. I didn't notice this message at first. It said "in process" before this screen shot

![image](https://github.com/kognetiks/chatbot-chatgpt/assets/6332663/7318e3ed-4e08-4761-9a5b-6f75df0b35e6)

I think your instructions need updating

**Comment by mayurjobanputra** [comment]
I added a PR with updated instructions

**Comment by mayurjobanputra** [comment]
I added a PR with updated instructions

**Comment by kognetiks** [comment]
Hello Mayur,

Agreed, the instructions need updating.  I've changed the text on the tab to read:

When you're ready to scan you website, set the 'Run Schedule' to one of the scheduldes (f. ex. 'Daily') then click 'Save Settings'.

This update will be included in the next release V 1.7.3.

The status will show as "In progress" until the cron job has finished, usually with in a few minutes.  Upon refreshing the page, you will see an update to status to "Completed" along with the date/time it finished and the number of content items analyzed.

Thank you for taking the time to share your valuable feedback, as it helps me continually improve and provide a better experience for our users.

Stephen
