### ISSUE TITLE
[Feature Request] Add Option to Customize API Endpoint Address

### ISSUE THREAD

**Issue by tzf1003** [kognetiks/chatbot-chatgpt#38]
Dear Developers,

I am a WordPress user from China, very interested in using your "Chatbot ChatGPT" plugin. However, due to the difficulties in directly accessing OpenAI's API from China, I propose a feature that would greatly enhance the usability of your plugin in similar situations.

The feature I am suggesting is the addition of a configuration option to customize the API endpoint. This would allow users to modify the default `https://api.openai.com` URL to point towards a mirror site that is accessible within China.

By implementing an option to change the API endpoint to a mirror site, users in regions with restricted access to OpenAI could still utilize the full functionality of your plugin. This enhancement would not only benefit me but also many other users in similar circumstances.

I hope you consider this addition as I believe it would significantly expand the accessibility and usability of your Chatbot ChatGPT plugin for WordPress users in restricted regions.

Thank you for considering this suggestion. I am looking forward to the possibility of smoothly integrating the Chatbot ChatGPT plugin into my WordPress site in the near future.

Best regards,
tzf1003

**Comment by kognetiks** [comment]
Hello, tzf1003,

In the latest version, on the "API/Model" tab of the Settings page for the plugin, at the bottom you will see where you can update the base URL.  This should allow you to use an alternative endpoint other than https://api.openai.com/v1.  However, be awared that there are different end points for different activities such as "/files", "/messages", etc.  If you find that that you're having difficulty after changing the "base URL", please let me know.

Respectfully,

Stephen

**Comment by tzf1003** [comment]
Thank you very much for your help! Following your guidance, I have successfully modified the API endpoint's base URL, and now the "Chatbot ChatGPT" plugin is running very smoothly on my WordPress site. Thank you for your hard work and outstanding achievements. I will close this issue, looking forward to more innovations and improvements in your plugin in the future. Wishing you all the best!

Best wishes,
tzf1003
